### PR TITLE
Added welcome message setting, default true

### PR DESCRIPTION
**Pull request by ToastyStoemp**
When having Account verification enabled, users received 2 mails while making an account, added a config setting to toggle the welcome message

### CODE REVIEW

**Comment by jedireza** [comment]
Thanks for creating a PR. Maybe not sending the welcome email during singup when `requireAccountVerification` is set to `true` is a better solution?

Keep in mind, these two emails contain different content and serve unique purposes.

**Comment by ToastyStoemp** [comment]
Perhaps sending a welcome message after a user has been verified as an option would also be interesting?

**Comment by jedireza** [comment]
If we do that without adding a new config settings, I'd probably be for it.

As it stands, this kind of change is something consumers could/should change on their own and I'm not sure it adds a lot of value being the default.

**Comment by ToastyStoemp** [comment]
Since both signup and verify - index.js files would require the format of the welcome message, would it be okay for you to move the formatting of both to uti/sendmail and add it to the options as a possible parameter. Maintaining the functionality of sending custom e-mails.

**Comment by jedireza** [comment]
I'm not sure I follow. The welcome email says hello and includes their username and email address. The verification email only has a link in it.

**Comment by ToastyStoemp** [comment]
If verification by email is disabled. the signup page will send a 'welcome-mail'

else the verification page sends a 'verify-mail', when successfully verified it sends a 'welcome-mail'

However this means that the the 'welcome-mail' function is duplicated, thus when you want to customize the 'welcome-mail' you might customize the wrong 'welcome-mail' function.

However if we move the options to the utility/sendmail then there is only 1 version of the 'welcome-mail'

**Comment by jedireza** [comment]
In it's current form these emails are simple and easy to maintain. This is a good example of something that the consumer should customize in their app.

Closing this PR for now. Thank you again for getting involved. 👍

**Pull request closed without merging**
