### PR TITLE
Remove bower, use npm (reference to #241)

### PR DESCRIPTION
**Pull request by fourq**
in reference to #241 

Here's what I did:

```
npm install --save backbone
npm install --save bootstrap@3.1.1
npm install --save font-awesome
npm install --save html5shiv
npm install --save query
npm install --save jquery.cookie
npm install --save moment
npm install --save respond.js
npm install --save underscore

rm ./bower.json

replaced copy task bower path with node
`:%s/bower_components/node_modules/gc`

npm install

remove bower_components/* from .gitignore

grunt lint
grunt
````

### CODE REVIEW

**Comment by fourq** [comment]
I updated this PR with another commit because I forgot to update the readme.

Hopefully I squashed them correctly.

**Comment by jedireza** [comment]
Thanks @fourq. The changes look good. I'll test them out locally as soon as I get a chance. I would like to get these four commits squashed into one though before merging.

**Comment by fourq** [comment]
Sorry, I'm really confused about why I cannot seem to squash these commits. I did this:

```
git rebase -i HEAD~2
```
changed the latest commit to squash
and then:
```
git push origin feature/from-bower-to-npm
```

but it it looks like I just keep tacking on more and more commits tot this. Should I create a different PR?

**Comment by fourq** [comment]
actually, I think I got it now. I wasn't using --force when I should have been it seems.

**Comment by jedireza** [comment]
Perfect. I tested locally and everything seems fine. Thanks for taking care of this!

**Pull request merged**
